language: java
branches:
  only:
    - A
    - master
    - dev
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean install
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: desh-travis-app